version: "3"
services:
  db:
    image: postgres:latest
    container_name: db_cont
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASES_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASS}
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped
  data-app:
    container_name: data-mgmnt-app
    # image: narendra121/mini-amazon:mini-amz
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db  
    restart: always
volumes:
  database_postgres:
 